# Generated by Django 5.2.3 on 2025-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='ai_generated_story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user_prompt',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
